# This file was generated by GoReleaser. DO NOT EDIT.
class Gridcli < Formula
  desc "This application simplifies the deployment of Grid."
  homepage "https://github.com/bbc/homebrew-gridcli"
  version "0.1.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bbc/gridcli/releases/download/v0.1.1/gridcli_0.1.1_darwin_amd64.tar.gz"
    sha256 "8ac089fc44ab426664cf4e892656b96ed8eeab91c560273eaa4a8ce75f295ee3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bbc/gridcli/releases/download/v0.1.1/gridcli_0.1.1_linux_amd64.tar.gz"
      sha256 "82509014290878d53f8ff66d263010175d3a04a33c17ca3622053c898000e89a"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bbc/gridcli/releases/download/v0.1.1/gridcli_0.1.1_linux_arm64.tar.gz"
        sha256 "4e7869a1ef95f85913be340c4d330a52e381e1acc93bf1ad907245c32a3230f8"
      else
        url "https://github.com/bbc/gridcli/releases/download/v0.1.1/gridcli_0.1.1_linux_arm.tar.gz"
        sha256 "4e6600bdf068632469680c0e6d4ea4904b075ae3072849b2f4d27fd7be5e8689"
      end
    end
  end

  def install
    bin.install "grid"
  end
end
