# This file was generated by GoReleaser. DO NOT EDIT.
class Gridcli < Formula
  desc "This application simplifies the deployment of Grid."
  homepage "https://github.com/bbc/homebrew-gridcli"
  version "0.1.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/bbc/gridcli/releases/download/v0.1.0/gridcli_0.1.0_darwin_amd64.tar.gz"
    sha256 "ff55581b129ceaf63c879f05f12f162175da4bdf9bb39ee4e19db55cca7778c8"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/bbc/gridcli/releases/download/v0.1.0/gridcli_0.1.0_linux_amd64.tar.gz"
      sha256 "39be60c5a2508854ec9b0892bcdf3981e4e596f38d6c9c7c0b4b959de827cdca"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bbc/gridcli/releases/download/v0.1.0/gridcli_0.1.0_linux_arm64.tar.gz"
        sha256 "48fdf984c07cbe53dc79a47584e4645889c32ae143bf57193b964421f432fb58"
      else
        url "https://github.com/bbc/gridcli/releases/download/v0.1.0/gridcli_0.1.0_linux_arm.tar.gz"
        sha256 "dc0c68f00a069c3ef29206501f06858745b48c67b29bad0019b7e336f34120f8"
      end
    end
  end

  def install
    bin.install "grid"
  end
end
